package:
  name: bioconductor-fdb.infiniummethylation.hg19
  version: 2.2.0
source:
  url: http://bioconductor.org/packages/release/data/annotation/src/contrib/FDb.InfiniumMethylation.hg19_2.2.0.tar.gz
  md5: b8b1abc599b9556b9fe9c6e824cb2697
build: 
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  skip: True # [osx]
requirements:
  build:
    - r-base ==3.3.1
    - bioconductor-annotationdbi
    - bioconductor-biostrings
    - bioconductor-genomicfeatures >=1.22.13
    - bioconductor-org.hs.eg.db
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
  run:
    - r-base 3.3.1
    - bioconductor-annotationdbi
    - bioconductor-biostrings
    - bioconductor-genomicfeatures >=1.22.13
    - bioconductor-org.hs.eg.db
    - bioconductor-txdb.hsapiens.ucsc.hg19.knowngene
test:
  commands:
    - $R -e "library('FDb.InfiniumMethylation.hg19')"
about:
  home: http://bioconductor.org/packages/release/data/annotation/html/FDb.InfiniumMethylation.hg19.html
  license: Artistic-2.0
  summary: 'Compiled HumanMethylation27 and HumanMethylation450 annotations'
