package:
  name: bioconductor-impute
  version: 1.48.0
source:
  fn: impute_1.48.0.tar.gz
  url: https://bioarchive.galaxyproject.org/impute_1.48.0.tar.gz
  md5: c80fe1cf61083779dfe956af3922d936
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - r-base
  run:
    - r-base
test:
  commands:
    - '$R -e "library(''impute'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/impute.html
  license: GPL-2
  summary: 'Imputation for microarray data (currently KNN only)'
