package:
  name: bioconductor-pd.hta.2.0
  version: 3.12.2
source:
  fn: pd.hta.2.0_3.12.2.tar.gz
  url: http://bioconductor.org/packages/release/data/annotation/src/contrib/pd.hta.2.0_3.12.2.tar.gz
  md5: 8e13f85ece49c38da73eaf7b2247f5f0
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biostrings >=2.35.12'
    - 'bioconductor-iranges >=2.1.43'
    - 'bioconductor-oligo >=1.31.5'
    - 'bioconductor-oligoclasses >=1.29.6'
    - 'bioconductor-s4vectors >=0.5.22'
    - r-base
    - 'r-dbi >=0.3.1'
    - 'r-rsqlite >=1.0.0'
  run:
    - 'bioconductor-biostrings >=2.35.12'
    - 'bioconductor-iranges >=2.1.43'
    - 'bioconductor-oligo >=1.31.5'
    - 'bioconductor-oligoclasses >=1.29.6'
    - 'bioconductor-s4vectors >=0.5.22'
    - r-base
    - 'r-dbi >=0.3.1'
    - 'r-rsqlite >=1.0.0'
test:
  commands:
    - '$R -e "library(''pd.hta.2.0'')"'
about:
  home: http://bioconductor.org/packages/release/data/annotation/html/pd.hta.2.0.html
  license: Artistic-2.0
  summary: 'Platform Design Info for Affymetrix HTA-2_0'
