{% set name = 'xlsx' %}
{% set version = '0.5.7' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-{{ name|lower }}
  version: {{ version|replace("-", "_") }}

source:
  fn: {{ name }}_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base
    - r-rjava
    - r-xlsxjars

  run:
    - r-base
    - r-rjava
    - r-xlsxjars

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('xlsx')"  # [not win]
    - "\"%R%\" -e \"library('xlsx')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://code.google.com/p/rexcel/, http://groups.google.com/group/R-package-xlsx
  license: GPL-3
  summary: Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file
    formats.
  license_family: GPL3

# The original CRAN metadata for this package was:

# Package: xlsx
# Type: Package
# Title: Read, write, format Excel 2007 and Excel 97/2000/XP/2003 files
# Version: 0.5.7
# Date: 2014-08-01
# Depends: rJava, xlsxjars
# LazyLoad: yes
# Author: Adrian A. Dragulescu
# Maintainer: Adrian A. Dragulescu <adrian.dragulescu@gmail.com>
# Description: Provide R functions to read/write/format Excel 2007 and Excel 97/2000/XP/2003 file formats.
# License: GPL-3
# URL: http://code.google.com/p/rexcel/, http://groups.google.com/group/R-package-xlsx
# BugReports: https://code.google.com/p/rexcel/issues/list
# Packaged: 2014-08-02 18:06:51 UTC; adrian
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-08-02 23:32:07

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
