package:
  name: bioconductor-geneplotter
  version: 1.52.0
source:
  fn: geneplotter_1.52.0.tar.gz
  url: https://bioarchive.galaxyproject.org/geneplotter_1.52.0.tar.gz
  md5: 8228e47578baae1f8112149c4c2a0a76
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - r-base
    - r-rcolorbrewer
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - bioconductor-biocgenerics
    - r-base
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''geneplotter'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/geneplotter.html
  license: Artistic-2.0
  summary: 'Functions for plotting genomic data'
