package:
  name: bioconductor-deseq
  version: 1.26.0
source:
  fn: DESeq_1.26.0.tar.gz
  url: https://bioarchive.galaxyproject.org/DESeq_1.26.0.tar.gz
  md5: ffa2d3e9b402b51aaeda07fcb82e8195
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biobase >=2.21.7'
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - r-base
    - r-locfit
    - r-rcolorbrewer
  run:
    - 'bioconductor-biobase >=2.21.7'
    - 'bioconductor-biocgenerics >=0.7.5'
    - bioconductor-genefilter
    - bioconductor-geneplotter
    - r-base
    - r-locfit
    - r-rcolorbrewer
test:
  commands:
    - '$R -e "library(''DESeq'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/DESeq.html
  license: 'GPL (>= 3)'
  summary: 'Estimate variance-mean dependence in count data from high-throughput sequencing
    assays and test for differential expression based on a model using the negative
    binomial distribution'
