package:
  name: bioconductor-biobase
  version: 2.34.0
source:
  fn: Biobase_2.34.0.tar.gz
  url: https://bioarchive.galaxyproject.org/Biobase_2.34.0.tar.gz
  md5: fd9f469fcc15a3d517e3e23a16739c9e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - 'bioconductor-biocgenerics >=0.3.2'
    - r-base
  run:
    - 'bioconductor-biocgenerics >=0.3.2'
    - r-base
test:
  commands:
    - '$R -e "library(''Biobase'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/Biobase.html
  license: Artistic-2.0
  summary: 'Functions that are needed by many other packages or which replace R functions.'
