package:
  name: bioconductor-genefilter
  version: 1.56.0
source:
  fn: genefilter_1.56.0.tar.gz
  url: https://bioarchive.galaxyproject.org/genefilter_1.56.0.tar.gz
  md5: fcb826566c0430990f8dd7cdd8f706dc
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  build:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-s4vectors >=0.9.42'
    - r-base
  run:
    - bioconductor-annotate
    - bioconductor-annotationdbi
    - bioconductor-biobase
    - 'bioconductor-s4vectors >=0.9.42'
    - r-base
test:
  commands:
    - '$R -e "library(''genefilter'')"'
about:
  home: http://bioconductor.org/packages/release/bioc/html/genefilter.html
  license: Artistic-2.0
  summary: 'Some basic functions for filtering genes'
